### ISSUE TITLE
Sidebar flicker

### ISSUE THREAD

**Issue by MarZab** [themekit/adminplus-bootstrap-theme#2]
The sidebar gets loaded last and tends to flicker.

AdminPlus.Sidebar.init()

I am using the pro version btw.

**Comment by lazabogdan** [comment]
Hi,

No flickering here using Safari. What browser?

**Comment by lazabogdan** [comment]
Actually, I just made a quick test on Chrome and Firefox as well and no flicker. Not sure how to replicate the issue

**Comment by MarZab** [comment]
I tried Safari as well on:
/adminplus-premium-v1.6.0/dist/1/index.html

Just click on dashboard multiple times.

**Comment by lazabogdan** [comment]
@MarZab I can see the sidebar gets displayed with a small delay on desktop, that's because it's mobile first. It's a compromise, the sidebars are hidden by default and get displayed by JavaScript on certain breakpoints. If it were the other way around it would have the same small delay only on mobile screens instead of only on desktop. 

We should be able to resolve this more elegantly.

However, I can't see the flicker you're seeing in any browser. Are you referring to the sidebar transition or something else?

**Comment by MarZab** [comment]
The "small delay" you see gets seen every time you switch pages so that is quite annoying. 

Any reason againts doing the breakpoints in CSS? This fixes the flickering for me btw.

```
<style>
    @media (min-width: 768px) {
      .sidebar-left {
          display: block;
      }
    }
</style>
```

**Comment by lazabogdan** [comment]
@MarZab,

The fixes are included with adminplus v1.0.0-alpha.9. It uses a new package called bootstrap-layout which includes everything related to the sidebar / layout. Please note you will also have to update your HTML markup.

I just updated our most simple boilerplate example to use adminplus v1.0.0-alpha.9 and bootstrap-layout v1.0.0-alpha.3 and there you can also see the new usage and the HTML markup.

See [adminplus-boilerplate-npm](https://github.com/themekit/adminplus-boilerplate-npm) source and a live [demo of the boilerplate](http://npm.adminplus-boilerplate.themekit.io/sidebar.html) which includes the fixes.

[AdminPlus Premium](http://themeforest.net/item/adminplus-premium-bootstrap-4-admin-dashboard/14601290) v1.7.0 should also be available today which includes the AdminPlus Lite and [Bootstrap Layout](https://github.com/themekit/bootstrap-layout) updates. You can see the live demo for this update already working [here](http://themeforest.net/item/adminplus-premium-bootstrap-4-admin-dashboard/full_screen_preview/14601290)

Thanks

**Comment by MarZab** [comment]
Sounds great! 

Btw, is there a premium only git repo out there? Something that I could just pull the changes in ?

**Comment by lazabogdan** [comment]
Sure, I can send you an invite to the private repo. 

But, I'd appreciate it if you could send a request first via a private message using the form on our [ThemeForest profile page](http://themeforest.net/user/mosaicpro). When you send the message, please use the same Envato account from which you purchased AdminPlus Premium.

Thanks

**Comment by MarZab** [comment]
Thank you :) :+1:
